name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

defaults:
  run:
    working-directory: ./code/AndroGUARD

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: set up a2p2
      run: curl -sS https://extgit.iaik.tugraz.at/fdraschbacher/a2p2/-/raw/main/a2p2_distribution_v1.0.1.zip?ref_type=heads&inline=false > a2p2_distribution.zip && unzip a2p2_distribution.zip && rm a2p2_distribution.zip 

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew assemblePatchPackages
